export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_ALBUMS_FETCHED = "USER_ALBUMS_FETCHED";
export const USER_PHOTOS_FETCHED = "USER_PHOTOS_FETCHED";
export const GET_USER_ALBUM_ID = "GET_USER_ALBUM_ID";

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
